language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml